# Generated by Django 5.2.3 on 2025-06-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_task_created_at_task_description_task_time_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
