# Generated by Django 5.2.3 on 2025-06-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_task_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly tasks', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20, null=True),
        ),
    ]
