# Generated by Django 5.2.3 on 2025-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_task_weekday_alter_task_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, help_text='When recurring task ends (optional)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='When recurring task starts', null=True),
        ),
    ]
