# Generated by Django 5.2.3 on 2025-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='#2d5a3d', help_text='Hex color code for the task (e.g., #FF5733)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time_of_day',
            field=models.TimeField(blank=True, help_text='End time of the task (optional)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_end_date',
            field=models.DateField(blank=True, help_text='When recurring task series ends (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date for one-time task or start date for recurring task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='Start time of the task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly tasks (0=Monday, 6=Sunday)', null=True),
        ),
    ]
