# Generated by Django 5.2.3 on 2025-06-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_remove_task_end_date_task_color_task_end_time_of_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, default='#AEC6CF', help_text='Hex color code for the task (e.g., #FF5733)', max_length=7, null=True),
        ),
    ]
